Upgrade to use swift 4.2
MediaMath/ios-sdk pull request #6
Opened 2019-04-02 00:36 UTC by mtjoe

This PR contains the following changes:
- Upgrade MMPixelSDK to use Swift 4.2

Upon upgrading a Swift 4.2, there was a few errors:
1. In `MMPixelSDK/MMPixelConfig.swift`, line 35 & 37:
  - `Overlapping accesses to 'name', but modification requires exclusive access; consider copying to a local variable`
  - Fixed by changing the 5th argument of `sysctl` to nil. This argument (`newval`) is not required to get the hardware name of the device.

2. In `MMPixelSDK/MMPixelSDK.swift`, line 107:
  - `Initializer for conditional binding must have Optional type, not 'UUID'`
  - Fixed by removing the conditional binding.

3. Tests `testGetAddlParamsString` and `testGetAddlParamsStringWithHashedEmail` failing 
  - Caused by the expected params string to have the wrong ordering to the addlParams. This is because Swift dictionaries do not have ordering. Therefore, upon creation of the `addlParams` dictionary, the ordering of the `addlParams` was changed.
  - Fixed by changing testing strategy to check whether each param is contained inside the generated string in different assertion statements.

2019-04-02 19:35 UTC, fsargent commented
This is great. I think you should be able to get the tests to pass by upgrading the .travis.yml with `xcode10.2`
https://docs.travis-ci.com/user/reference/osx/#xcode-version

2019-04-02 20:08 UTC, FodT requested changes
Thanks for this PR! 
Right now, the travis build is failing. Can you update `.travis.yml` to use `xcode10.2` ?

2019-04-02 22:24 UTC, mtjoe commented
Travic CI is passing now 👍

2019-04-03 14:27 UTC, FodT approved these changes
Thank you!

2019-04-03 14:28 UTC, merged